# Generated by Django 5.0.1 on 2024-03-26 08:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalArrivalTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('totalDepartureTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('totalStopTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('totalPostTravelTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('totalChargingTime', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('nodeTo', models.CharField(default='0', max_length=20)),
                ('nodeFrom', models.CharField(default='0', max_length=20)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeFrom', models.CharField(default='0', max_length=20)),
                ('nodeTo', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('nodeNo', models.CharField(default='0', max_length=20)),
                ('density', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=14, default=0, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=14, default=0, max_digits=20)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='mapApp.link')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivalTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('departureTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('carId', models.CharField(default='1', max_length=20)),
                ('status', models.CharField(default='0', max_length=200)),
                ('battery', models.IntegerField(default=100)),
                ('passengerChange', models.IntegerField(default=0)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapApp.link')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('pickTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('dropTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('nodeTo', models.CharField(default='0', max_length=20)),
                ('nodeFrom', models.CharField(default='0', max_length=20)),
                ('waitedTime', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='mapApp.car')),
            ],
        ),
    ]
