# Generated by Django 5.0 on 2024-01-18 06:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('carId', models.CharField(default='1', max_length=20)),
                ('node', models.CharField(default='0', max_length=20)),
                ('status', models.CharField(default='0', max_length=20)),
                ('battery', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeNo', models.CharField(default='0', max_length=20)),
                ('coordinates', models.IntegerField(default=0)),
                ('status', models.CharField(default='0', max_length=20)),
                ('density', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitedTime', models.IntegerField(default=0)),
                ('origin', models.CharField(default='0', max_length=20)),
                ('destination', models.CharField(default='0', max_length=20)),
                ('pickTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dropTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapApp.car')),
            ],
        ),
    ]
