# Generated by Django 5.0.1 on 2024-05-16 04:53

import datetime
import django.db.models.deletion
import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationId', models.CharField(default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.CharField(default='1', max_length=20)),
                ('stationTime', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='arrivalTime',
        ),
        migrations.RemoveField(
            model_name='car',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='car',
            name='carId',
        ),
        migrations.RemoveField(
            model_name='car',
            name='departureTime',
        ),
        migrations.RemoveField(
            model_name='car',
            name='link',
        ),
        migrations.RemoveField(
            model_name='car',
            name='passengerChange',
        ),
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='totalArrivalTime',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='totalChargingTime',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='totalDepartureTime',
        ),
        migrations.RemoveField(
            model_name='route',
            name='density',
        ),
        migrations.RemoveField(
            model_name='route',
            name='nodeNo',
        ),
        migrations.RemoveField(
            model_name='route',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='car',
            name='geometry',
            field=djgeojson.fields.LineStringField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default='Feature', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='carId',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='maxWaitedTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='totalEmptyTripLength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='totalServiceLength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='geom',
            field=djgeojson.fields.LineStringField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='geometry',
            field=djgeojson.fields.LineStringField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.CharField(default='Feature', max_length=20),
        ),
        migrations.CreateModel(
            name='CarProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.CharField(default='1', max_length=20)),
                ('nodeFrom', models.CharField(default='0', max_length=20)),
                ('nodeTo', models.CharField(default='0', max_length=20)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('arrivalTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('departureTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('lastChargeTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(default='0', max_length=200)),
                ('battery', models.IntegerField(default=100)),
                ('passengerChange', models.IntegerField(default=0)),
                ('travelDistance', models.FloatField(default=0)),
                ('stopTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('passedLink', djgeojson.fields.LineStringField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='mapApp.car')),
            ],
        ),
        migrations.AlterField(
            model_name='passenger',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='mapApp.carproperties'),
        ),
        migrations.CreateModel(
            name='ChargeLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.CharField(default='1', max_length=20)),
                ('timeArrival', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('timeCharged', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('stationId', models.CharField(default='1', max_length=20)),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chargeLap', to='mapApp.dashboarddata')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('passengerCount', models.IntegerField(default=0)),
                ('carId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengerData', to='mapApp.dashboarddata')),
            ],
        ),
        migrations.CreateModel(
            name='RouteProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('nodeNo', models.CharField(default='0', max_length=20)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='mapApp.route')),
            ],
        ),
    ]
