# Generated by Django 5.0 on 2024-01-18 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='carId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='mapApp.car'),
        ),
    ]
