# Generated by Django 5.0 on 2024-01-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0002_alter_passenger_carid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='timeStamp',
            field=models.TimeField(blank=True),
        ),
    ]
