# Generated by Django 5.0 on 2024-01-19 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0003_alter_car_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='timeStamp',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='dropTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='pickTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
