# Generated by Django 5.0 on 2024-01-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0004_alter_car_timestamp_alter_passenger_droptime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='status',
        ),
    ]
