# Generated by Django 5.0 on 2024-01-20 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0005_remove_route_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='coordinates',
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('routeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='mapApp.route')),
            ],
        ),
    ]
