# Generated by Django 5.0 on 2024-01-20 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0006_remove_route_coordinates_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='timeStamp',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
