# Generated by Django 5.0 on 2024-01-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0007_route_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='node',
            new_name='nodeFrom',
        ),
        migrations.AddField(
            model_name='car',
            name='nodeTo',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
