# Generated by Django 5.0 on 2024-01-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0008_rename_node_car_nodefrom_car_nodeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='nodeFrom',
            new_name='node',
        ),
        migrations.RemoveField(
            model_name='car',
            name='nodeTo',
        ),
    ]
