# Generated by Django 5.0 on 2024-01-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0009_rename_nodefrom_car_node_remove_car_nodeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='node',
            new_name='nodeNumber',
        ),
    ]
