# Generated by Django 5.0 on 2024-01-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0010_rename_node_car_nodenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='nodeNumber',
            new_name='node',
        ),
    ]
