# Generated by Django 5.0.1 on 2024-01-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0012_alter_car_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
