# Generated by Django 5.0.1 on 2024-03-26 09:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0012_alter_car_battery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalArrivalTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('totalDepartureTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('totalStopTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('totalPostTravelTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('totalChargingTime', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('nodeTo', models.CharField(default='0', max_length=20)),
                ('nodeFrom', models.CharField(default='0', max_length=20)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeFrom', models.CharField(default='0', max_length=20)),
                ('nodeTo', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='timeStamp',
            new_name='arrivalTime',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='destination',
            new_name='nodeFrom',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='origin',
            new_name='nodeTo',
        ),
        migrations.RemoveField(
            model_name='car',
            name='node',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='lattitude',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='routeId',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='carId',
        ),
        migrations.AddField(
            model_name='car',
            name='departureTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='car',
            name='passengerChange',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='lat',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='lng',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='callTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='passenger',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='mapApp.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapApp.link'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='mapApp.link'),
            preserve_default=False,
        ),
    ]
