# Generated by Django 5.0.1 on 2024-03-27 03:11

import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0013_dashboarddata_demand_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='link',
        ),
        migrations.AddField(
            model_name='car',
            name='geometry',
            field=djgeojson.fields.LineStringField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='nodeFrom',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='nodeTo',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='link',
            name='geom',
            field=djgeojson.fields.LineStringField(default=0),
            preserve_default=False,
        ),
    ]
