# Generated by Django 5.0.1 on 2024-01-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0013_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
