# Generated by Django 5.0.1 on 2024-01-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0014_car_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='lattitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='car',
            name='position',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='routeId',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='positions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='mapApp.car'),
            preserve_default=False,
        ),
    ]
