# Generated by Django 5.0.1 on 2024-03-27 03:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0014_remove_car_link_car_geometry_car_nodefrom_car_nodeto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='arrivalTime',
        ),
        migrations.RemoveField(
            model_name='car',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='car',
            name='carId',
        ),
        migrations.RemoveField(
            model_name='car',
            name='departureTime',
        ),
        migrations.RemoveField(
            model_name='car',
            name='nodeFrom',
        ),
        migrations.RemoveField(
            model_name='car',
            name='nodeTo',
        ),
        migrations.RemoveField(
            model_name='car',
            name='passengerChange',
        ),
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default='Feature', max_length=20),
        ),
        migrations.CreateModel(
            name='CarProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeFrom', models.CharField(default='0', max_length=20)),
                ('nodeTo', models.CharField(default='0', max_length=20)),
                ('arrivalTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('departureTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('carId', models.CharField(default='1', max_length=20)),
                ('status', models.CharField(default='0', max_length=200)),
                ('battery', models.IntegerField(default=100)),
                ('passengerChange', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='mapApp.car')),
            ],
        ),
        migrations.AlterField(
            model_name='passenger',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='mapApp.carproperties'),
        ),
    ]
