# Generated by Django 5.0.1 on 2024-03-27 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0015_remove_car_arrivaltime_remove_car_battery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproperties',
            name='arrivalTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
