# Generated by Django 5.0.1 on 2024-01-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0015_rename_lattitude_coordinates_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='positions',
            new_name='carId',
        ),
    ]
