# Generated by Django 5.0.1 on 2024-03-27 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0017_alter_carproperties_arrivaltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproperties',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
