# Generated by Django 5.0.1 on 2024-04-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0019_alter_carproperties_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carproperties',
            old_name='nodeFrom',
            new_name='node',
        ),
        migrations.RemoveField(
            model_name='carproperties',
            name='nodeTo',
        ),
    ]
