# Generated by Django 5.0.1 on 2024-01-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0020_alter_coordinates_lat_alter_coordinates_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='node',
            new_name='nodeFrom',
        ),
        migrations.AddField(
            model_name='car',
            name='nodeTo',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
