# Generated by Django 5.0.1 on 2024-04-03 10:56

import djgeojson.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0021_rename_node_carproperties_nodefrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproperties',
            name='passedLink',
            field=djgeojson.fields.LineStringField(default=0),
            preserve_default=False,
        ),
    ]
