# Generated by Django 5.0.1 on 2024-04-04 04:42

import datetime
import django.db.models.deletion
import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0022_carproperties_passedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='density',
        ),
        migrations.RemoveField(
            model_name='route',
            name='nodeNo',
        ),
        migrations.RemoveField(
            model_name='route',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='route',
            name='geometry',
            field=djgeojson.fields.LineStringField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.CharField(default='Feature', max_length=20),
        ),
        migrations.CreateModel(
            name='RouteProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('nodeNo', models.CharField(default='0', max_length=20)),
                ('route', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='mapApp.route')),
            ],
        ),
    ]
