# Generated by Django 5.0.1 on 2024-02-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0022_rename_destination_passenger_nodefrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='carId',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='mapApp.car'),
        ),
    ]
