# Generated by Django 5.0.1 on 2024-04-04 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0023_remove_route_density_remove_route_nodeno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeproperties',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='mapApp.route'),
        ),
    ]
