# Generated by Django 5.0.1 on 2024-04-04 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0024_alter_routeproperties_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeproperties',
            name='route',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='mapApp.route'),
        ),
    ]
