# Generated by Django 5.0.1 on 2024-02-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0024_remove_coordinates_calltime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='carId',
        ),
    ]
