# Generated by Django 5.0.1 on 2024-02-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0025_remove_passenger_carid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='number',
            new_name='amount',
        ),
    ]
