# Generated by Django 5.0.1 on 2024-04-10 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0025_alter_routeproperties_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproperties',
            name='lastChargeTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
