# Generated by Django 5.0.1 on 2024-04-10 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0026_carproperties_lastchargetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproperties',
            name='lastChargeTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
