# Generated by Django 5.0.1 on 2024-04-13 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0027_alter_carproperties_lastchargetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationDepartureTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.CharField(default='1', max_length=20)),
                ('stationDepartureTime', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
