# Generated by Django 5.0.1 on 2024-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0027_alter_passenger_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='amount',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
