# Generated by Django 5.0.1 on 2024-05-02 04:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0028_dashboarddata_carid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargelap',
            old_name='chargeLap',
            new_name='lap',
        ),
        migrations.RenameField(
            model_name='dashboarddata',
            old_name='totalArrivalTime',
            new_name='maxWaitedTime',
        ),
        migrations.RemoveField(
            model_name='chargelap',
            name='tripLengthToCharge',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='totalChargingTime',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='totalDepartureTime',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='totalPostTravelTime',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='totalStopTime',
        ),
        migrations.AddField(
            model_name='chargelap',
            name='timeArrival',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='chargelap',
            name='timeCharged',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='chargelap',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chargeLap', to='mapApp.carproperties'),
        ),
    ]
