# Generated by Django 5.0.1 on 2024-02-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0028_alter_passenger_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
