# Generated by Django 5.0.1 on 2024-04-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0028_stationdeparturetimedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StationDepartureTimeData',
            new_name='StationDepartureTime',
        ),
    ]
