# Generated by Django 5.0.1 on 2024-05-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0029_rename_chargelap_chargelap_lap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='maxWaitedTime',
            field=models.IntegerField(default=0),
        ),
    ]
