# Generated by Django 5.0.1 on 2024-05-02 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0030_alter_dashboarddata_maxwaitedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='totalPostTravelTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='totalStopTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
