# Generated by Django 5.0.1 on 2024-02-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0030_passenger_carid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='carId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='mapApp.car'),
        ),
    ]
