# Generated by Django 5.0.1 on 2024-02-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0031_alter_passenger_carid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='timeStamp',
            new_name='arrivalTime',
        ),
    ]
