# Generated by Django 5.0.1 on 2024-05-02 06:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0031_dashboarddata_totalposttraveltime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='totalEmptyTripLength',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='totalServiceLength',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PassengerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('PassengerCount', models.IntegerField(default=0)),
                ('carId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengerData', to='mapApp.dashboarddata')),
            ],
        ),
    ]
