# Generated by Django 5.0.1 on 2024-05-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0032_alter_dashboarddata_totalemptytriplength_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengercount',
            old_name='PassengerCount',
            new_name='passengerCount',
        ),
        migrations.AlterField(
            model_name='chargelap',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chargeLap', to='mapApp.dashboarddata'),
        ),
    ]
