# Generated by Django 5.0.1 on 2024-02-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0032_rename_timestamp_car_arrivaltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='carId',
            new_name='car',
        ),
    ]
