# Generated by Django 5.0.1 on 2024-05-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0033_rename_passengercount_passengercount_passengercount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproperties',
            name='travelDistance',
            field=models.FloatField(default=0),
        ),
    ]
