# Generated by Django 5.0.1 on 2024-02-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0033_rename_carid_passenger_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='passengerChange',
            field=models.IntegerField(default=0),
        ),
    ]
