# Generated by Django 5.0.1 on 2024-05-02 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0034_carproperties_traveldistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproperties',
            name='stopTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
