# Generated by Django 5.0.1 on 2024-03-14 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0034_car_passengerchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='departureTime',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
