# Generated by Django 5.0.1 on 2024-03-19 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0035_car_departuretime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='nodeFrom',
        ),
        migrations.RemoveField(
            model_name='car',
            name='nodeTo',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='car',
        ),
        migrations.CreateModel(
            name='LinkCoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeFrom', models.CharField(default='0', max_length=20)),
                ('nodeTo', models.CharField(default='0', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='mapApp.car')),
            ],
        ),
        migrations.AddField(
            model_name='coordinates',
            name='link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='mapApp.linkcoor'),
            preserve_default=False,
        ),
    ]
