# Generated by Django 5.0.1 on 2024-05-08 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0035_carproperties_stoptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.CharField(default='1', max_length=20)),
                ('stationTime', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
