# Generated by Django 5.0.1 on 2024-03-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0036_remove_car_nodefrom_remove_car_nodeto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkcoor',
            name='car',
        ),
    ]
