# Generated by Django 5.0.1 on 2024-03-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0037_remove_linkcoor_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkCoor',
            new_name='Link',
        ),
    ]
