# Generated by Django 5.0.1 on 2024-03-19 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0038_rename_linkcoor_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mapApp.link'),
            preserve_default=False,
        ),
    ]
