# Generated by Django 5.0.1 on 2024-03-19 06:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0039_car_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callTime', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('nodeTo', models.CharField(default='0', max_length=20)),
                ('nodeFrom', models.CharField(default='0', max_length=20)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapApp.link'),
        ),
    ]
